services:
  wordpress:
    image: wordpress
    ports:
      - "82:80"
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - redDocker

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
    networks:
      - redDocker
networks:
  redDocker: