version: '3'
services:
  app:
    build:
      context: .
      args:
        - IMAGE_VERSION=3.7.0-alpine3.8
    image: dodero/flask-redis:1.0
    environment:
      - FLASK_ENV=development
    ports:
      - "81:84:5000"
    networks:
      - mynet
  redis:
    image: redis:4.0.11-alpine
    volumes:
      - mydata:/data
    networks:
      - mynet
volumes:
  mydata:
networks:
  mynet: