name: 'Marp to generate PDF and list changed files'
run-name: ${{ github.actor }} is generating a list of changed PDF with marp
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  generate_docker_pdf:
    name: Generate PDF from docker markdown
    if: github.repository == 'uca-virtualizacion/docker'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: marp/package-lock.json
      - name: Install npm
        run: npm install
        working-directory: './marp'
      - name: Install marp-cli
        run: npm install @marp-team/marp-cli
        working-directory: './marp'
      - name: Install marpit
        run: npm install @marp-team/marpit
        working-directory: './marp'
      - name: Install marp-core
        run: npm install @marp-team/marp-core
        working-directory: './marp'
      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        with:
          fileOutput: ''
      - name: Show files changed
        run: cat $HOME/files.txt
      - name: Generate PDFs
        run:
          for filename in `cat $HOME/files.txt`
          do
            if [[ $filename == *.md ]]
            then
              echo Processing ${filename%%.md}...
              marp --allow-local-files --config-file ./marp/marp-engine.js --pdf $1.md --pdf-outlines --pdf-outlines.pages=false --pdf-outlines.headings=true
            fi
          done
      - name: List changed PDF files
        run:
          for pdffile in pdf/*.pdf
          do
              [ -e "$pdffile" ] || continue
              echo File changed... "$pdffile"
          done
